// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddImagesToBoard is the only board-population mechanism (see "New image
 * -> board assignment" — placement is always explicit, never inferred).
 */
export function AddImagesToBoard(repoPath: string, boardID: number, imageIDs: number[] | null): $CancellablePromise<void> {
    return $Call.ByID(2681465777, repoPath, boardID, imageIDs);
}

/**
 * BoardsForImage powers the list view's "show on board" cross-navigation —
 * callers prompt the user to pick when an image is on more than one board.
 */
export function BoardsForImage(repoPath: string, imageID: number): $CancellablePromise<$models.BoardSummary[] | null> {
    return $Call.ByID(897892924, repoPath, imageID);
}

export function CreateBoard(repoPath: string, name: string): $CancellablePromise<$models.BoardSummary | null> {
    return $Call.ByID(426844435, repoPath, name);
}

export function DeleteBoard(repoPath: string, boardID: number): $CancellablePromise<void> {
    return $Call.ByID(1852201914, repoPath, boardID);
}

export function ListBoards(repoPath: string): $CancellablePromise<$models.BoardSummary[] | null> {
    return $Call.ByID(668901860, repoPath);
}

export function RemoveImagesFromBoard(repoPath: string, boardID: number, imageIDs: number[] | null): $CancellablePromise<void> {
    return $Call.ByID(324987213, repoPath, boardID, imageIDs);
}

export function RenameBoard(repoPath: string, boardID: number, name: string): $CancellablePromise<void> {
    return $Call.ByID(2393179673, repoPath, boardID, name);
}

/**
 * SetLayoutMode is not itself logged to the undo stack — see Stage 5 report
 * notes: the mode toggle is a view preference, not a data mutation with a
 * meaningful "undo" in the same sense as the position changes it triggers.
 */
export function SetLayoutMode(repoPath: string, boardID: number, mode: string): $CancellablePromise<void> {
    return $Call.ByID(1191281174, repoPath, boardID, mode);
}
