// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * GroupService manages `groups` — a generic image *set* (variants, angle
 * turnarounds, sequences), distinct from `relationships`' parent/child
 * derivation edges. See the edge<->group interaction rules in the spec:
 * relationship edges always attach to a specific member image, a group can
 * never itself be an edge's source, and removing a member keeps its edges.
 * 
 * Group mutations are not currently wired into the Stage 5 undo log — the
 * spec's minimum undo list (link/unlink, archive/trash, tags, board
 * membership, position) doesn't name groups, and creating/dissolving a set
 * is comparatively rare and easy to redo by hand; this is a deliberate
 * scope cut, not an oversight.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function AddMember(repoPath: string, groupID: number, imageID: number): $CancellablePromise<void> {
    return $Call.ByID(3759557883, repoPath, groupID, imageID);
}

export function CreateGroup(repoPath: string, name: string, kind: string, imageIDs: number[] | null): $CancellablePromise<$models.GroupInfo | null> {
    return $Call.ByID(776638829, repoPath, name, kind, imageIDs);
}

/**
 * RemoveMember detaches imageID but keeps its relationship edges intact —
 * it becomes a standalone image again. If fewer than 2 members would
 * remain, the group is dissolved (see store.RemoveGroupMember).
 */
export function RemoveMember(repoPath: string, groupID: number, imageID: number): $CancellablePromise<void> {
    return $Call.ByID(1527990452, repoPath, groupID, imageID);
}

export function SetCover(repoPath: string, groupID: number, imageID: number): $CancellablePromise<void> {
    return $Call.ByID(266314469, repoPath, groupID, imageID);
}

export function Ungroup(repoPath: string, groupID: number): $CancellablePromise<void> {
    return $Call.ByID(2201106324, repoPath, groupID);
}
