// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function LinkSource(repoPath: string, sourceID: number, derivedID: number): $CancellablePromise<void> {
    return $Call.ByID(3100663929, repoPath, sourceID, derivedID);
}

/**
 * LoadBoard scans repoPath for newly discovered media, generates thumbnails
 * for anything missing one, flags files no longer found on disk, and
 * returns everything needed to render the (currently single, implicit)
 * canvas. Stage 1 has no board concept yet — every non-trashed image in the
 * repo lives on this one canvas.
 */
export function LoadBoard(repoPath: string): $CancellablePromise<$models.BoardData | null> {
    return $Call.ByID(3370418912, repoPath);
}

export function SetArchived(repoPath: string, imageID: number, archived: boolean): $CancellablePromise<void> {
    return $Call.ByID(1258308906, repoPath, imageID, archived);
}

export function SetPosition(repoPath: string, imageID: number, x: number, y: number): $CancellablePromise<void> {
    return $Call.ByID(336031175, repoPath, imageID, x, y);
}

/**
 * TrashImage flags an image as trashed, hiding it from the board. See
 * store.SetTrashed for why this doesn't yet move the file to .loom/trash/.
 */
export function TrashImage(repoPath: string, imageID: number): $CancellablePromise<void> {
    return $Call.ByID(2678142843, repoPath, imageID);
}

export function UnlinkSource(repoPath: string, relationshipID: number): $CancellablePromise<void> {
    return $Call.ByID(1877800166, repoPath, relationshipID);
}
