// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetImage resolves a single image's info by ID, independent of any board —
 * used by the Detail panel (Stage 9) to show an image that isn't a member of
 * the currently-loaded board (e.g. reached via a Library/Explorer ctrl/cmd+
 * click on an image that lives elsewhere). Wraps the previously-unused
 * store.ListImagesByIDs with a single-element slice rather than adding a new
 * store-level single-row query.
 */
export function GetImage(repoPath: string, imageID: number): $CancellablePromise<$models.ImageInfo | null> {
    return $Call.ByID(1073816885, repoPath, imageID);
}

export function LinkSource(repoPath: string, sourceID: number, derivedID: number): $CancellablePromise<void> {
    return $Call.ByID(3100663929, repoPath, sourceID, derivedID);
}

/**
 * LinkSourceToGroup fans out a source->member edge to every member of a
 * collapsed group being dropped onto — a group can never itself be the
 * derived (or source) end of an edge, only its members can. See the
 * edge<->group interaction rules in the spec.
 */
export function LinkSourceToGroup(repoPath: string, sourceID: number, groupID: number): $CancellablePromise<void> {
    return $Call.ByID(3292999851, repoPath, sourceID, groupID);
}

/**
 * ListDirectory lists relPath (relative to repoPath), non-recursively.
 * Every media file it finds is registered in the images table first (the
 * same INSERT OR IGNORE idiom ScanAndRegisterImages uses for repo-wide
 * discovery), so every returned file always has a real row — drag-and-drop
 * from Explorer never needs to special-case "not yet imported".
 */
export function ListDirectory(repoPath: string, relPath: string): $CancellablePromise<$models.DirListing | null> {
    return $Call.ByID(1985619183, repoPath, relPath);
}

/**
 * LoadBoard scans repoPath for newly discovered media, generates thumbnails
 * for anything missing one, flags files no longer found on disk, and
 * returns everything needed to render one board's canvas — only images
 * explicitly placed on boardID (see "New image -> board assignment": scan
 * discovery never auto-places an image on any board).
 */
export function LoadBoard(repoPath: string, boardID: number): $CancellablePromise<$models.BoardData | null> {
    return $Call.ByID(3370418912, repoPath, boardID);
}

/**
 * MoveFile renames/moves an image's file to newRelPath (relative to
 * repoPath) and logs the move as an undoable step. Both undo and redo of
 * this step reuse store.MoveFile — see moveFileStepPayload in
 * undo_service.go for how the forward/inverse pair is built by swapping
 * which relative path is the target.
 */
export function MoveFile(repoPath: string, imageID: number, newRelPath: string): $CancellablePromise<[string, string]> {
    return $Call.ByID(2053037199, repoPath, imageID, newRelPath);
}

/**
 * RestoreImage un-flags a previously trashed image.
 */
export function RestoreImage(repoPath: string, imageID: number): $CancellablePromise<void> {
    return $Call.ByID(2477729643, repoPath, imageID);
}

export function SetArchived(repoPath: string, imageID: number, archived: boolean): $CancellablePromise<void> {
    return $Call.ByID(1258308906, repoPath, imageID, archived);
}

/**
 * SetPosition persists one node's dragged position (manual-layout mode) and
 * logs it as a single-entry undo step, capturing the prior position as the
 * inverse.
 */
export function SetPosition(repoPath: string, imageID: number, x: number, y: number): $CancellablePromise<void> {
    return $Call.ByID(336031175, repoPath, imageID, x, y);
}

/**
 * SetPositions applies a batch of position updates as a single undo step —
 * used by "auto-arrange selection" and by applying a computed auto-layout,
 * so undoing a one-shot arrange action reverts the whole cluster in one
 * step rather than one step per node.
 */
export function SetPositions(repoPath: string, updates: $models.PositionUpdate[] | null): $CancellablePromise<void> {
    return $Call.ByID(1001501276, repoPath, updates);
}

/**
 * TrashImage flags an image as trashed, hiding it from the board, and
 * physically moves the file into .loom/trash/ (see store.SetTrashed).
 */
export function TrashImage(repoPath: string, imageID: number): $CancellablePromise<void> {
    return $Call.ByID(2678142843, repoPath, imageID);
}

export function UnlinkSource(repoPath: string, relationshipID: number): $CancellablePromise<void> {
    return $Call.ByID(1877800166, repoPath, relationshipID);
}
