// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * LibraryService backs the Stage 4 list/library view — the same underlying
 * image rows as the canvas, queried without board scoping and enriched
 * with tags/boards for table display.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ListImages runs query against the repo and returns display-ready rows —
 * search targets prompt text, filename, tag names, and board names (all
 * via SQL LIKE, adequate at this app's scale — see spec, Stage 4).
 */
export function ListImages(repoPath: string, query: $models.LibraryQuery): $CancellablePromise<$models.LibraryRow[] | null> {
    return $Call.ByID(2405448916, repoPath, query);
}
