// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface BoardData {
    "boardId": number;
    "boardName": string;
    "layoutMode": string;
    "images": ImageInfo[] | null;
    "relationships": RelationshipInfo[] | null;
    "groups": GroupInfo[] | null;
}

export interface BoardSummary {
    "id": number;
    "name": string;
    "layoutMode": string;
    "imageCount": number;
}

/**
 * DirListing is Explorer's non-recursive view of one directory under the
 * repo root: subdirectory names plus every media file in it, reusing
 * ImageInfo's shape (same fields LoadBoard and Library return) so Explorer
 * can share their row rendering rather than needing its own shape.
 */
export interface DirListing {
    "relPath": string;
    "dirs": string[] | null;
    "files": ImageInfo[] | null;
}

export interface GroupInfo {
    "id": number;
    "name": string;
    "kind": string;
    "coverImageId": number;
    "memberIds": number[] | null;
}

export interface ImageInfo {
    "id": number;
    "fileName": string;
    "filePath": string;
    "thumbUrl": string;
    "fullUrl": string;
    "width": number;
    "height": number;
    "archived": boolean;
    "trashed": boolean;
    "missing": boolean;
    "canvasX": number;
    "canvasY": number;
    "canvasW": number;
    "canvasH": number;
    "promptText": string;
    "groupId": number;
    "createdAt": string;
}

export interface LibraryQuery {
    "search": string;

    /**
     * 0 = any, -1 = unassigned
     */
    "boardId": number;

    /**
     * "" / "active" / "archived" / "trashed" / "all"
     */
    "status": string;
    "tagId": number;
}

export interface LibraryRow {
    "id": number;
    "fileName": string;
    "filePath": string;
    "thumbUrl": string;
    "promptText": string;
    "tags": string[] | null;
    "boards": string[] | null;
    "createdAt": string;
    "archived": boolean;
    "trashed": boolean;
    "missing": boolean;
}

export interface PositionUpdate {
    "imageId": number;
    "x": number;
    "y": number;
}

export interface PromptInfo {
    "id": number;
    "name": string;
    "text": string;
    "negative": string;
    "usageCount": number;
}

export interface RelationshipInfo {
    "id": number;
    "sourceImageId": number;
    "derivedImageId": number;
}

export interface RepoInfo {
    "id": string;
    "name": string;
    "path": string;
    "imageCount": number;
    "openedAt": string;

    /**
     * IsOpen reports whether this repo currently has a live window showing
     * it (used by ListRecentRepos so the recent-repos list can flag entries
     * that are already open elsewhere).
     */
    "isOpen": boolean;

    /**
     * OpenedElsewhere is set on the return value of open/SwitchTo when the
     * requested repo turned out to already be open in another window. That
     * window was focused instead of reusing/creating one for the caller, so
     * the calling window's frontend must NOT navigate itself into this
     * repo. Only ID/Path are populated alongside it — the calling window
     * isn't navigating, so there's no need to bootstrap the repo again just
     * to fill in Name/ImageCount/OpenedAt.
     */
    "openedElsewhere": boolean;
}

export interface TagInfo {
    "id": number;
    "name": string;
}

export interface UndoResult {
    "applied": boolean;
    "kind"?: string;
    "error"?: string;
}

export interface UndoState {
    "canUndo": boolean;
    "canRedo": boolean;
}
