// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface BoardData {
    "boardId": number;
    "boardName": string;
    "layoutMode": string;
    "images": ImageInfo[] | null;
    "relationships": RelationshipInfo[] | null;
    "groups": GroupInfo[] | null;
}

export interface BoardSummary {
    "id": number;
    "name": string;
    "layoutMode": string;
    "imageCount": number;
}

export interface GroupInfo {
    "id": number;
    "name": string;
    "kind": string;
    "coverImageId": number;
    "memberIds": number[] | null;
}

export interface ImageInfo {
    "id": number;
    "fileName": string;
    "filePath": string;
    "thumbUrl": string;
    "fullUrl": string;
    "width": number;
    "height": number;
    "archived": boolean;
    "trashed": boolean;
    "missing": boolean;
    "canvasX": number;
    "canvasY": number;
    "promptText": string;
    "groupId": number;
    "createdAt": string;
}

export interface LibraryQuery {
    "search": string;

    /**
     * 0 = any, -1 = unassigned
     */
    "boardId": number;

    /**
     * "" / "active" / "archived" / "trashed" / "all"
     */
    "status": string;
    "tagId": number;
}

export interface LibraryRow {
    "id": number;
    "fileName": string;
    "filePath": string;
    "thumbUrl": string;
    "promptText": string;
    "tags": string[] | null;
    "boards": string[] | null;
    "createdAt": string;
    "archived": boolean;
    "trashed": boolean;
    "missing": boolean;
}

export interface PositionUpdate {
    "imageId": number;
    "x": number;
    "y": number;
}

export interface RelationshipInfo {
    "id": number;
    "sourceImageId": number;
    "derivedImageId": number;
}

export interface RepoInfo {
    "id": string;
    "name": string;
    "path": string;
    "imageCount": number;
    "openedAt": string;
}

export interface TagInfo {
    "id": number;
    "name": string;
}

export interface UndoResult {
    "applied": boolean;
    "kind"?: string;
    "error"?: string;
}

export interface UndoState {
    "canUndo": boolean;
    "canRedo": boolean;
}
