// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface BoardData {
    "images": ImageInfo[] | null;
    "relationships": RelationshipInfo[] | null;
}

export interface ImageInfo {
    "id": number;
    "fileName": string;
    "filePath": string;
    "thumbUrl": string;
    "width": number;
    "height": number;
    "archived": boolean;
    "missing": boolean;
    "canvasX": number;
    "canvasY": number;
    "promptText": string;
}

export interface RelationshipInfo {
    "id": number;
    "sourceImageId": number;
    "derivedImageId": number;
}

export interface RepoInfo {
    "id": string;
    "name": string;
    "path": string;
    "imageCount": number;
    "openedAt": string;
}
