// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * PromptService backs the manual prompt attach/reuse picker (docs/init.md
 * Stage 1: "browse-and-pick list over the managed prompt library... backed
 * by FindOrCreate-by-hash so picking and dedup don't fight"). Prompt
 * automation from generation tooling is explicitly out of scope — every
 * prompt in the library got there because a user typed or picked one.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AttachPrompt points imageID at an existing prompt from the library
 * (the "reuse" half of the picker).
 */
export function AttachPrompt(repoPath: string, imageID: number, promptID: number): $CancellablePromise<void> {
    return $Call.ByID(3253964016, repoPath, imageID, promptID);
}

/**
 * CreateAndAttachPrompt finds-or-creates a prompt by text+negative (dedup
 * key) and attaches it to imageID — the "manual attach" half of the
 * picker, for a prompt that isn't in the library yet.
 */
export function CreateAndAttachPrompt(repoPath: string, imageID: number, name: string, text: string, negative: string): $CancellablePromise<$models.PromptInfo | null> {
    return $Call.ByID(3543532627, repoPath, imageID, name, text, negative);
}

/**
 * DetachPrompt clears whatever prompt imageID has attached, if any.
 */
export function DetachPrompt(repoPath: string, imageID: number): $CancellablePromise<void> {
    return $Call.ByID(3248330174, repoPath, imageID);
}

/**
 * ListPrompts returns the whole managed prompt library for the picker's
 * browse list.
 */
export function ListPrompts(repoPath: string): $CancellablePromise<$models.PromptInfo[] | null> {
    return $Call.ByID(3538626306, repoPath);
}
