// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CreateRepo prompts the user to pick or create a folder and opens it as a
 * repo. Functionally identical to OpenFolder — a repo is just a folder with
 * a .loom/ — the separate entry point exists for the native dialog's
 * wording and for the native "new folder" affordance most OS pickers offer.
 */
export function CreateRepo(): $CancellablePromise<$models.RepoInfo | null> {
    return $Call.ByID(2401034657);
}

/**
 * ListRecentRepos returns the global recent-repos list, most recently
 * opened first. Entries that no longer exist on disk are silently dropped.
 */
export function ListRecentRepos(): $CancellablePromise<$models.RepoInfo[] | null> {
    return $Call.ByID(214100739);
}

/**
 * OpenFolder prompts the user to pick an existing folder and opens it as a
 * repo (bootstrapping .loom/ if this is the first time).
 */
export function OpenFolder(): $CancellablePromise<$models.RepoInfo | null> {
    return $Call.ByID(1414549085);
}

/**
 * OpenRecent re-opens an already-known repo by path (e.g. clicking a row in
 * the recent-repos list).
 */
export function OpenRecent(path: string): $CancellablePromise<$models.RepoInfo | null> {
    return $Call.ByID(2243340126, path);
}

/**
 * SwitchTo opens path in a brand-new top-level window rather than the
 * calling window. It exists for the repo-switcher (Stage 10): when a
 * window already showing repo A wants to switch to repo B, it must never
 * navigate itself away from A, so — unlike open/OpenRecent — this method
 * never reuses "the current window" as the destination.
 * 
 * If path is already open somewhere, that window is focused instead of
 * creating a duplicate.
 */
export function SwitchTo(path: string): $CancellablePromise<$models.RepoInfo | null> {
    return $Call.ByID(3428967684, path);
}
