// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SettingsService is a thin key/value wrapper over the repo-scoped settings
 * table, used by panel visibility/dock-side (Stage 7) and the Settings
 * screen (Stage 11). Layout mode does NOT go through here — it keeps using
 * boards.layout_mode via BoardService.SetLayoutMode.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

/**
 * Get returns the value stored under key, or "" if it has never been set
 * (see store.GetSetting) — an unset setting is not an error, just an
 * unconfigured default.
 */
export function Get(repoPath: string, key: string): $CancellablePromise<string> {
    return $Call.ByID(1690046152, repoPath, key);
}

/**
 * Set upserts key's value.
 */
export function Set(repoPath: string, key: string, value: string): $CancellablePromise<void> {
    return $Call.ByID(1238884500, repoPath, key, value);
}
