// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SystemService wraps small OS-native affordances that don't belong to any
 * one repo/image concept — currently just "reveal in file explorer".
 * Wails v3's application package has no built-in helper for this (checked
 * pkg/application — only dialogs/clipboard/browser-open), so this shells
 * out per-OS the way the spec anticipated.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

/**
 * IsServerMode reports whether this binary is running as a headless web
 * server rather than a native desktop app. The frontend uses it to decide
 * between native-only affordances (folder-picker dialogs, spawning new OS
 * windows, revealing files in the local file explorer) and their
 * browser-appropriate substitutes.
 */
export function IsServerMode(): $CancellablePromise<boolean> {
    return $Call.ByID(2538539852);
}

/**
 * RevealInFileExplorer opens the OS file browser with path selected (where
 * the platform tool supports selection) or, failing that, its containing
 * folder open.
 */
export function RevealInFileExplorer(path: string): $CancellablePromise<void> {
    return $Call.ByID(3822521199, path);
}
