// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddTag attaches tagName to imageID, creating the tag (free-form, no
 * managed taxonomy — see data model docs) if this is the first time it's
 * been used.
 */
export function AddTag(repoPath: string, imageID: number, tagName: string): $CancellablePromise<$models.TagInfo | null> {
    return $Call.ByID(1159539620, repoPath, imageID, tagName);
}

export function ListTags(repoPath: string): $CancellablePromise<$models.TagInfo[] | null> {
    return $Call.ByID(2125305908, repoPath);
}

export function RemoveTag(repoPath: string, imageID: number, tagID: number): $CancellablePromise<void> {
    return $Call.ByID(699661107, repoPath, imageID, tagID);
}

export function TagsForImage(repoPath: string, imageID: number): $CancellablePromise<$models.TagInfo[] | null> {
    return $Call.ByID(3253872428, repoPath, imageID);
}
