// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * UndoService exposes the operation log to the frontend. Undo/Redo are
 * best-effort: if applying the inverse/forward step fails (most notably
 * because its target image was hard-purged since the operation was
 * recorded), the cursor does not move and the failure reason is returned
 * for the frontend to surface (e.g. as a toast) rather than silently
 * dropped.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Redo(repoPath: string): $CancellablePromise<$models.UndoResult | null> {
    return $Call.ByID(755923059, repoPath);
}

export function State(repoPath: string): $CancellablePromise<$models.UndoState | null> {
    return $Call.ByID(4103662568, repoPath);
}

export function Undo(repoPath: string): $CancellablePromise<$models.UndoResult | null> {
    return $Call.ByID(2251419281, repoPath);
}
